### ISSUE TITLE
Consensus Algorithm

### ISSUE THREAD

**Issue by tbrand** [tbrand/SushiCoin#1]
Currently, cheep PoW is implemented.
Should rethink about it.

A (Short) Guide to Blockchain Consensus Protocols
https://www.coindesk.com/short-guide-blockchain-consensus-protocols/

**Comment by tbrand** [comment]
- [ ] To prevent GPU mining, implement many conditional branches as consensus algorithm.

**Comment by tbrand** [comment]
https://twitter.com/AtaKuyumcu/status/949247719591284736

**Comment by tbrand** [comment]
https://blog.visvirial.com/articles/519

**Comment by tbrand** [comment]
http://www.bitcoinlion.com/cryptocurrency-mining-hash-algorithms/

**Comment by tbrand** [comment]
https://github.com/SushiProject/SushiCoin/blob/aca12aec8ac2b25570066cff54bce8c27c2f7632/src/core/miner/miner.cr#L13

**Comment by watzon** [comment]
So is the goal to have this be only minable with the cpu?

**Comment by tbrand** [comment]
Realistically, it's difficult. But yeah, I aim to there.

I have a plan to create Android and iOS sdk or app for mining SushiCoin :smile:
Or may be browser based implementation is good from the aspect of cross platform.

**Comment by tbrand** [comment]
Let me close the issue since I've merge the PR.
If we have to rethink about this, we can reopen or create new issue.
Thanks!

**Comment by alexcrownjr** [comment]
try this one https://github.com/browep/brower-walk
