### ISSUE TITLE
Open gitter channel

### ISSUE THREAD

**Issue by watzon** [tbrand/SushiCoin#24]
It would be nice to have a gitter, telegram, discord, or slack channel where we can discuss the development of this. I love Crystal, I also love Sushi, and I love the idea of bringing more exposure to Crystal through crypto currencies. I'd be very interested in helping with this project, but we need a place that devs and potential devs can chat.

**Comment by tbrand** [comment]
Thanks for the proposal! I will open a slack channel! Let me invite forks.
I also be able to invite you to here as contributor, what do you think?

**Comment by tbrand** [comment]
Join our Slack from here!!
https://join.slack.com/t/sushicoin/shared_invite/enQtMzAxMjgxNjc3NzQ4LTZiYjIyZDkzN2ZhMWQ5OGVhZTg5OTg0YjhlN2YwMzQxYWQ5ZjM1NGIwNWRhNzI4ZTcyMTNmMTdkYmEzY2RmMDU

I'll update README.md.

**Comment by tbrand** [comment]
Done.

**Comment by watzon** [comment]
@tbrand I'd love to be added as a contributor. I already got the project forked and running. Great job!
